# Generated by Django 3.0.8 on 2021-06-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='priduct_description',
            new_name='product_description',
        ),
    ]
