# Generated by Django 3.0.8 on 2021-06-05 04:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210604_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_available',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
