# Generated by Django 3.0.8 on 2021-06-09 03:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_product_stock_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='Customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
