# Generated by Django 3.0.8 on 2021-06-09 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_product_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
    ]
